[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://attendease-backend-ovl6.onrender.com/api"
  NODE_VERSION = "18.20.4"