services:
  - type: web
    name: attendease-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: attendease-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: attendease-db
    databaseName: attendease
    user: attendease_user
    plan: free